# Problem 1

In [354]:
# 1 - numpy kütüphanesini import edin

import numpy as a 

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin

m = a.random.randint(0,10, 5)
print(m)

# 3 - matris'in boyutunu öğrenin

v = a.shape(m)
print(m)


# 4 - matris'i yeniden boyutlandırın
v = m.reshape(5,1)
print(v)

# 5 - matris'in boyut sayısını öğrenin

print(m.ndim)


[1 2 8 2 0]
[1 2 8 2 0]
[[1]
 [2]
 [8]
 [2]
 [0]]
1


# Problem 2

In [376]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin

m = a.arange(1, 10, 2)
print(m)

# 2 - Oluşturduğunuz matrisi parçalayın

v, b, c = a.split(m, [1, 3])
print(v)
print(b)
print(c)

# 3 - Parçalanmış matrisleri birleştirin
print(a.concatenate([v, b, c]))



[1 3 5 7 9]
[1]
[3 5]
[7 9]
[1 3 5 7 9]


# Problem 3

In [427]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin

m = a.random.randint(5, 100)
m = a.array([m, m+2, m+4, m+6, m+8, m+10, m+12, m+14, m+16, m+18])
print(m)

# 2 - matris'in özelliklerini inceleyin

print(m.ndim)
print(m.shape)
print(m.size)
print(m.dtype)


[17 19 21 23 25 27 29 31 33 35]
1
(10,)
10
int64


In [433]:
print(10 and 20)
print(10 or 20)

20
10
