# Problem 1 

In [240]:
# 1 - numpy kütüphanesini import edin

import numpy as a

# 2 - 5 elemanlı bir numpy array oluşturun

c = a.random.randint(5, 100, 5)
print(c)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
c  = a.sort(c)
print(c)


[48 45 24 48 35]
[24 35 45 48 48]


# Problem 2

In [275]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.

d = a.array([10,15,30,45,60])
print(d)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
 
d = a.arange(5, 15)
print(d)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.

d = a.arange(50, 100, 5)
print(d)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.

d = a.zeros(10)
print(d)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.

d = a.ones(10)
print(d)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.



# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.

d = a.random.randint(10, 30, 5)
print(d)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.

d = a.random.randint(-1, 1, 10)
print(d)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.

d = a.random.randint(10, 50, 15)
v = d.reshape(3, 5)
print(v)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?

v =  v.ndim()
print(v)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?



# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?


# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.


# 14- Üretilen dizinin elemanlarını tersten yazdırın.


# 15- Üretilen matrisin ilk satırını seçiniz.


# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?


# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.


# 18- Üretilen matrisin her bir elemanının karesini alınız.


# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.


[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[20 29 13 20 13]
[ 0  0  0  0 -1 -1 -1 -1 -1  0]
[[24 22 13 27 42]
 [18 17 47 10 44]
 [39 45 28 26 46]]


TypeError: 'int' object is not callable