# Problem 1 

In [6]:
# 1 - numpy kütüphanesini import edin

import numpy as a

# 2 - 5 elemanlı bir numpy array oluşturun

c = a.random.randint(5, 100, 5)
print(c)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
c  = a.sort(c)
print(c)


[33 47 90 42 41]
[33 41 42 47 90]


# Problem 2

In [185]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.

d = a.array([10,15,30,45,60])
print(d)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
 
d = a.arange(5, 15)
print(d)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.

d = a.arange(50, 100, 5)
print(d)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.

d = a.zeros(10)
print(d)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.

d = a.ones(10)
print(d)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.



# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.

d = a.random.randint(10, 30, 5)
print(d)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.

d = a.random.randint(-1, 1, 10)
print(d)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.

d = a.random.randint(10, 50, 15)
b = d
v = d.reshape(3, 5)
print(v)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?

d.sort()
print(d[0])
print(d[-1])
print(sum(d) / len(d))

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?

# print((d[-1].index))
print(len(d)-1)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.

d = a.arange(10,20)
print(d[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.

print(d[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.

print(v, '\n')

print(v[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?

print(v[2][3])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.

for i in range(len(v)):
    print(v[i][0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.

print(v**2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.

d = a.random.randint(-50, 50, 15)
print('.............................................................')
for i in d:
    if i>0 and i %2 == 0:
        print(i)

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[12 25 23 12 10]
[-1 -1  0  0  0 -1  0  0  0 -1]
[[49 22 34 17 43]
 [14 48 30 20 42]
 [17 24 18 31 20]]
14
49
28.6
14
[10 11 12]
[19 18 17 16 15 14 13 12 11 10]
[[14 17 17 18 20]
 [20 22 24 30 31]
 [34 42 43 48 49]] 

[14 17 17 18 20]
48
14
20
34
[[ 196  289  289  324  400]
 [ 400  484  576  900  961]
 [1156 1764 1849 2304 2401]]
.............................................................
38
18
26
